### ISSUE TITLE
Support for Azure Blob storage

### ISSUE THREAD

**Issue by rolanddb** [confluentinc/kafka-connect-storage-cloud#124]
Hi,
We would like to see an additional module in this project to support Azure blob storage as a sink.
We implemented a PoC based on the Azure Java SDK. This is working fine based on some preliminary tests.

What I noticed is that there is quite some code that could be common/shared between various implementations such as S3 / AZ / GCP. We hardly had to change the SinkTask or TopicPartitionWriter. Also the format.avro.* and format.json.* classes are almost unchanged.
Most of the change is of course in the storage class, and the config classes.

Do you have any thoughts about how the packages can be refactored to keep things DRY? I'm thinking about an additional module 'kafka-connect-storage-cloud-common' that would contain the shared classes.

I'd be happy to contribute a PR, though I'm hesitant about big refactorings because it will take some time and if you don't accept it, it would be a waste of our time :)

Interested to hear your thoughts.

Roland

**Comment by kkonstantine** [comment]
Hi @rolanddb 

the initiative sounds great. This repo has been implemented with extensibility in mind, and that's one of the reasons it was called `storage-cloud` from the beginning. As a PoC it would make more sense to me to start with a new module under the current repo that marks `kafka-connect-s3` as a dependency. Any transient dependencies that will be brought in, can be excluded during the packaging of the connector. Any small changes that facilitate class extension can be ported to S3 directly. 

We could follow this path initially before attempting a more general refactoring that would flesh out all the common parts into a `common` module under `kafka-connect-storage-cloud`. `kafka-connect-storage-common` was created to flesh out the common parts between cloud objects stores and hdfs (and potentially others). That's why it's a separate repo. `cloud-common` would reside in this repo as a submodule, but as you say we probably don't want to start with that. 

I've started considering a change in the test mock that would allow us to test against other object store APIs too. Let me know what you think.

**Comment by rolanddb** [comment]
@kkonstantine Thanks for the quick reply.

That makes sense, I can give it a try. 

One more question - I branched off from 3.3.1-post because the 4.0.x required me to clone a lot of other repos. Which branch `kafka-connect-storage-cloud` would you recommend as a base?

**Comment by kkonstantine** [comment]
That would be `master` at this point, since it's definitely a new feature. 

I wouldn't expect something to change significantly between 3.3.1 and 4.0.x in terms of repo requirement. 

You don't have to clone the other repos. You just have to check them out locally, `mvn clean install` them and that way you'll have the snapshot versions available locally (since snapshots are not published to a public maven repo). Here's the list of repos you need: 

https://github.com/confluentinc/kafka-connect-storage-common/wiki/FAQ

**Comment by rolanddb** [comment]
Ok, I started again from `master`  and pushed to `https://github.com/Eneco/kafka-connect-storage-cloud/tree/feature/support-az-blob-storage`.

The build is quite strict with style checking - do you have a configuration for IntelliJ that conforms to the checks? I didn't feel like fixing everything by hand so I build it with -Dcheckstyle.skip=true ;)

**Comment by omnipresentminded** [comment]
I was looking for Azure Blob storage support as well

**Comment by aakashnshah** [comment]
We have a separate Azure Blob Storage Sink Connector now - https://www.confluent.io/hub/confluentinc/kafka-connect-azure-blob-storage

Since the issue looks resolved, I will close it.
