### ISSUE TITLE
Does it supports parquet format?

### ISSUE THREAD

**Issue by psuryawanshi** [confluentinc/kafka-connect-storage-cloud#26]
We have kafka events needs to write on S3 with parquet format.. just would like to know does this connector supports this format?

**Comment by ewencp** [comment]
@psuryawanshi Parquet is not supported yet, but support is planned. However, there are some challenges due to the way Parquet itself is implemented against the HDFS filesystem API.

**Comment by wdaehn** [comment]
+1

**Comment by cricket007** [comment]
@ewencp Perhaps someone could merge in this code? 
https://github.com/qubole/streamx/tree/master/src/main/java/io/confluent/connect/hdfs/parquet

**Comment by ewencp** [comment]
As mentioned above
> However, there are some challenges due to the way Parquet itself is implemented against the HDFS filesystem API.
I haven't taken a close look, but I think that parquet support only works if you're using an HDFS layer on the store. We specifically wrote a different connector because there are a bunch of issues with trying to do that and get good delivery semantics. My understanding is that the parquet library is not properly abstracted away from some assumptions about HDFS being available, so it's not trivial and the code linked would not work directly (for example, it uses `org.apache.parquet.avro.AvroParquetWriter` that requires an HDFS configuration be passed to it).

**Comment by scarr** [comment]
Are there any timelines on when this feature might be released?

**Comment by cricket007** [comment]
@ewencp You mention delivery semantics... Does that imply work been done to use HDFS Connect with the `s3a://` protocol and the Parquet support provided in that project?

**Comment by Igosuki** [comment]
The HDFS connector uses a WAL file on HDFS, which S3 does not support, so it's unlikely the feature will ever come to it. I think Parquet support in this component is a lot more likely, since partition writers here just stage and commit files. 
See: https://github.com/confluentinc/kafka-connect-storage-cloud/blob/master/kafka-connect-s3/src/main/java/io/confluent/connect/s3/TopicPartitionWriter.java#L481

**Comment by Igosuki** [comment]
The streamx fork is interesting, but imo it's a lesser solution than secor (https://github.com/pinterest/secor), since it requires some kind of setup to replace the WAL, for instance a database but why would you spend IO on a db when you can just write to the local fs and do two stage commits.

**Comment by cricket007** [comment]
@Igosuki Did you see #130 that does Parquet to Azure? Do you think that could be ported?

BTW,  I've got confirmation from Qubole they don't seem focused on supporting Streamx as Kafka Connect HDFS makes updates. 

https://github.com/Eneco/kafka-connect-storage-cloud/blob/589566438c2a2982eb8af9d4944ee9572c820eba/kafka-connect-azure/src/main/java/io/confluent/connect/azblob/format/parquet/ParquetRecordWriterProvider.java

**Comment by eliasah** [comment]
The committer working on #172 seemed to have stopped working on fixing that PR, any idea on what gonna happen ?

**Comment by canelmas** [comment]
Good news! #241

**Comment by Navgeet** [comment]
Can we close this @ewencp?

**Comment by kkonstantine** [comment]
I thought I'd wait for the release, but let's close it, indeed. 
This feature will appear in Confluent Platform `v5.4.0`
