### ISSUE TITLE
Upgrade version of aws sdk to > 1.11.623

### ISSUE THREAD

**Issue by jdamata** [confluentinc/kafka-connect-storage-cloud#288]
I would like to leverage the IAM roles for service account solution outlined here: https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/

This requires that the aws sdk be of a version that supports AWS_ROLE_ARN and AWS_WEB_IDENTITY_TOKEN_FILE environment variables.

Supported SDK version are:
https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html

**Comment by jdamata** [comment]
https://github.com/confluentinc/kafka-connect-storage-cloud/pull/294

**Comment by aakashnshah** [comment]
I will review the associated PR and get an additional reviewer on it as well. Will close this as it is addressed.

**Comment by kkonstantine** [comment]
Reopening this issue, since it's common practice to close issues with associated PRs when these PRs are merged or closed/not applicable anymore. 

Given that we are in code freeze for 5.4, which will also be the next Confluent release, I've chosen to wait for the release so we don't have to partially backport. 

@aakashnshah please close again this issue when the fix is in.

**Comment by aakashnshah** [comment]
@kkonstantine understood, thank you!

**Comment by kkonstantine** [comment]
Resolved by: https://github.com/confluentinc/kafka-connect-storage-cloud/pull/306

**Comment by olegelantsev** [comment]
Hi @jdamata , I tried to use an upgraded version of S3 connector, but found that AWS 1.11.725 fails to authenticate with AWS_ROLE_ARN and AWS_WEB_IDENTITY_TOKEN_FILE because of missing STS AWS library.

Default provider lists failures, one of which is for WebIdentity provider:
```
WebIdentityTokenCredentialsProvider: To use assume role profiles the aws-java-sdk-sts module must be on the class path.
```
After I added missing dependency in a class path, `getCredentials()` worked.

Did you provide aws-java-sdk-sts-1.11.725.jar in class path separately? As it's missing in S3 Connector, unfortunately.
