### ISSUE TITLE
Unable to access S3SinkConnectorConfig in custom RecordWriterProvider

### ISSUE THREAD

**Issue by steveratay** [confluentinc/kafka-connect-storage-cloud#40]
The following line of code passes a null to the first argument of the RecordWriterProvider.getRecordWriter(final S3SinkConnectorConfig conf, final String filename) call.  Is there a reason for passing null here? I think S3SinkConnectorConfig is an instance variable of TopicPartitionWriter, and it would be helpful to be able to access this configuration object when writing a custom RecordWriterProvider implementation.

https://github.com/confluentinc/kafka-connect-storage-cloud/blob/master/kafka-connect-s3/src/main/java/io/confluent/connect/s3/TopicPartitionWriter.java#L286

**Comment by ewencp** [comment]
@steveratay Thanks for pointing this out! This was just an oversight during refactoring -- we had been considering removing the parameter entirely since none of the `RecordWriterProvider`'s we included need them. However, since it's part of the interface still, we should pass that in.

It looks like this is already being fixed in https://github.com/confluentinc/kafka-connect-storage-cloud/pull/37 as a side effect of that change requiring config to be available in the `RecordWriterProvider`, so you should see the fix when that PR is merged.

**Comment by steveratay** [comment]
Thanks for pointing out the fix is in the existing PR.  I also found a workaround by calling .conf() on the S3Storage object.  Unfortunately I don't see a way to be able to pass in additional configuration parameters though, which is ultimately what I need to do.  Am I missing something?

I get the following exception:
```
org.apache.kafka.common.config.ConfigException: Unknown configuration 'csv.keys'
	at io.confluent.connect.s3.S3SinkConnectorConfig.get(S3SinkConnectorConfig.java:207)
```

**Comment by ewencp** [comment]
@steveratay The `get` method is supposed to only return valid values for configs that the `S3SinkConnectorConfig` knows about. You can use `originals()`, `originalsStrings()`, or `originalsWithPrefix()` to get at a `Map` containing all the original config key-value pairs or a subset containing only those with a specified prefix (if you want to namespace the configs your provider uses).

**Comment by steveratay** [comment]
Thanks, those methods worked.
