### ISSUE TITLE
Extra "/" with TimeBasedPartitioner

### ISSUE THREAD

**Issue by morganhferry** [confluentinc/kafka-connect-storage-cloud#54]
We realized an issue today when using the TimeBasedPartitioner (specifically, we are using the DailyPartitioner which automatically writes folder names up until day). 

When using this partitioner we see the following behavior: [topics.dir]/[topicname]/year=2017/month=06/day=07//[filename]

There is an extra "/" after the partition and before the filename.

When using the FieldPartitioner we do not see this behavior. From what I can tell, the class that returns the partition when using the TimeBasedPartitioner returns a "/", but the class that returns the partition when using the FieldPartitioner does not. The code in the S3 connector adds a "/". Therefore, when using the TimeBasedPartitioner, it results in an extra "directory" with a blank name.

I think this error lies in getCommitFilename and fileKeyToCommit. We can certainly remove the "/" from the code in the S3 connector, but that means that when using the FieldPartitioner, we will be missing a directory delimiter, screwing up the directory names / combining them.

**Comment by kkonstantine** [comment]
This is an artifact of a change in `path.format` property. The convention has changed and now a user should not include a trailing directory separator at the end of the format. This is reflected in the config property's doc, but it's easy to miss. 

We felt this change was necessary to support both cloud and hdfs connectors on top of [storage-common](https://github.com/confluentinc/kafka-connect-storage-common). 

Try if you wish with `path.format` not including the trailing `/` and see if the issue goes away.

**Comment by morganhferry** [comment]
Thanks, Konstantine. We had not actually set path.format and were using the out of the box DailyPartitioners format - we will go ahead and explicitly list the format we would like, but it might be good to note that out of the box, using the default settings for that partitioner will cause this issue - unless I am missing something? Is it appropriate to have that default changed? Even the documentation for the connector shows this:

"For example, if you set path.format='year'=YYYY/'month'=MM/'day'=dd/'hour'=HH/, the data directories will have the format /year=2015/month=12/day=07/hour=15"

Will including a "/" at the end actually result in a format that does not include that slash? It appears this is what this documentation would imply.

Either way, we will go ahead and test, passing in our own format. Thanks!

**Comment by kkonstantine** [comment]
@morganhferry thanks for clarifying. I wasn't able to replicate with the DailyPartitioner in unit tests. 
Are we referring to the same partitioner? Maybe you are using a previous release?

The related lines I see in storage-common are the following: 
https://github.com/confluentinc/kafka-connect-storage-common/blob/3.2.x/partitioner/src/main/java/io/confluent/connect/storage/partitioner/DailyPartitioner.java#L32
and format with its doc: 
https://github.com/confluentinc/kafka-connect-storage-common/blob/3.2.x/partitioner/src/main/java/io/confluent/connect/storage/partitioner/PartitionerConfig.java#L65-L70

I referenced the 3.2.x branch since the changes have been backported there too. If you are referring to a branch or tag referencing a previous release you are right. These changes will appear in the forthcoming releases 3.2.2 and 3.3.0 of the connector. (Thus, they are present in branches 3.2.x and master at the moment).

**Comment by kkonstantine** [comment]
@morganhferry did you manage to set your `path.format` correctly?
I believe we should close this ticket at this point.

**Comment by kkonstantine** [comment]
This must have been resolved in the most recently released versions. Closing.

**Comment by morganhferry** [comment]
Yes - we have verified that this has been resolved in the most recent version. Thank you.
