### ISSUE TITLE
small avro file after schema migration

### ISSUE THREAD

**Issue by harksin** [confluentinc/kafka-connect-storage-cloud#66]
hello,
 i'm using confluent s3 connector with this config :

```{
  "name": "s3-connector-events-v2",
  "config": {
    "connector.class": "io.confluent.connect.s3.S3SinkConnector",
    "s3.region":"eu-west-1",
    "s3.bucket.name":"avrodata",
    "s3.part.size":5242880,
    "flush.size":220000,
    "storage.class":"io.confluent.connect.s3.storage.S3Storage",
    "format.class":"io.confluent.connect.s3.format.avro.AvroFormat",
    "schema.generator.class":"io.confluent.connect.storage.hive.schema.TimeBasedSchemaGenerator",
    "key.converter":"org.apache.kafka.connect.storage.StringConverter",
    "partitioner.class":"io.confluent.connect.storage.partitioner.TimeBasedPartitioner",
    "partition.duration.ms":600000,
    "locale":"fr",
    "timezone":"UTC",
    "topics.dir":"kafka-connect-v2",
    "path.format":"'year'=YYYY/'month'=MM/'day'=dd/'hour'=HH",
    "tasks.max": "1",
    "topics": "avro-events",
    "name": "s3-connector-event-v2"
  }
}
```
Last month this task produce and store  ~100mo files.
Today i have deployed a new avro schema on this topic.
Now i have 3-5KB files. (1-3 item by files).
It sounds like `flush.size` is no more used.

i don't know if this is an issue or a config mistake, but any help is welcome.

thanks by advance

**Comment by klamouri** [comment]
Are you still producing old version of the event at the same time?

If so you can read upon this documentation: 
http://docs.confluent.io/current/connect/connect-storage-cloud/kafka-connect-s3/docs/s3_connector.html#configuration

Specifically about `schema.compatibility` and follow the link about HDFS documentation. The behavior is the same

**Comment by harksin** [comment]
No, there is just new version :).
Thanks for the tips about `schema.compatibility`, i just added it to my conf as `"schema.compatibility":"BACKWARD"` (my schema registry is on "BACKWARD" mode ).
But sadly this does not solve my issue.

**Comment by ewencp** [comment]
@harksin The `schema.compatibility` helps in the case that we see commonly where doing, e.g., a rolling bounce of your app results in a period during which you have both schemas interleaved. It sounds like something else might be going on in your case and it definitely sounds odd. If you have only one schema in that range of data, then it should only roll to a new file based on the other criteria you've defined (e.g. `flush.size` or `rotate.interval.ms`).

Can you verify that sequential files both do, in fact, contain the same schema? And whether the files definitely have a different number of records per file (which would indicate it could not be an misconfiguration of `flush.size`). You could also try turning on TRACE level logging, there are some messages at that level that give information about when we're checking whether to rotate to a new file or not, which would indicate what condition is being hit that causes rotation. (There is also one exception that can be found via info logs, it'd be a message that looks like `Starting commit and rotation for topic partition {} with start offset {}` which indicates that we're hitting `flush.size`-based rotation.)

**Comment by harksin** [comment]
Hello,
Thank you for your reply and sorry for the delay, I convoyed my sailboat.
In the end, this is not an issue.
One of my services continued to push an old payload. So I had 2 versions on the same subject.
My bad, thank you very much for your help.

Harksin

**Comment by woodlee** [comment]
For anyone else who happens along: I encountered a similar problem upon creating an S3 sink connector attached to a topic that already had a couple months' of accumulated data in it when using the `RecordField` timestamp extractor. It appeared that the `rotate.interval.ms` was being evaluated against differences in the timestamps pulled from the Avro data payloads rather than against wall time. Records earlier in my topic were sparse enough that the intervals between their timestamps were often longer than the rotation interval, so I had lots of files with just one or two records each. My solution was to just delete the `rotate.interval.ms` property from the connector's config until the initial "catch-up" was complete, such that `flush.size` became the main determinant of file rotation.

On a probably-related note, I've observed that this connector usually has a persistent lag as observed with the consumer group command, _if_ there aren't new records coming into the connected topic(s). Based on the above, my hunch is that it takes a new record coming in to trigger the evaluation against `rotate.interval.ms`... so if you have a few records that haven't been flushed to S3 by other rotation-triggering conditions at the end of your initial load, the connector will just sit there and never do anything with them until the next record happens to come along.

**Comment by kkonstantine** [comment]
Combining `rotate.interval.ms` with the appropriate `TimestampExtractor` (e.g [WallclockTimestampExtractor](https://github.com/confluentinc/kafka-connect-storage-common/blob/master/partitioner/src/main/java/io/confluent/connect/storage/partitioner/TimeBasedPartitioner.java#L211)) could be another way to achieve what you want. To flush records on a streaming pipeline where streaming pauses at times you can combine any partitioning with `scheduling.rotate.interval.ms`. In this case of course (either by using WallclockTimestampExtractor, `scheduling.rotate.interval.ms`, or both) you might see duplicates upon restarts or reprocessing of older data.

**Comment by woodlee** [comment]
👍 It totally had not occurred to me to add in `rotate.schedule.interval.ms` to solve the issue, but indeed doing so fixed the lag issue while allowing me to keep the `RecordField` timestamp extractor. Thanks for the pointer!
