### ISSUE TITLE
Document local development flow

### ISSUE THREAD

**Issue by jklukas** [confluentinc/kafka-connect-storage-cloud#94]
In order to be able to run a simple `mvn test` on the master branch here, it's necessary to clone and build a cascade of dependencies. It would be great to have an easier path, but if that's the intended workflow, I'd love to see if documented, either in the README here or in some central location for the confluent tools and then linked in the README.

**Comment by pranavoyo** [comment]
+1

**Comment by kkonstantine** [comment]
This happens because snapshot versions of the dependent projects are not published to a public repo. 

`kafka-connect-storage-cloud` depends on `kafka-connect-storage-common`.

Feel free to read: 
https://github.com/confluentinc/kafka-connect-storage-common/wiki/FAQ
and see what's the required order with respect to building dependencies that will allow you to build this connector from master.

**Comment by jklukas** [comment]
@kkonstantine - That's exactly the kind of guidance that's needed to be able to build and contribute to this project, and I'd love to see that advice codified in the README.

Here's a proposed change to do that: https://github.com/confluentinc/kafka-connect-storage-cloud/pull/105

**Comment by kkonstantine** [comment]
Notes and link were added to the README.
